CREATE TABLE INGREDIENT (
  meal_id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  contains_lactose BOOLEAN NOT NULL,
  vegetarian BOOLEAN NOT NULL,
  vegan BOOLEAN NOT NULL,
  gluten_free BOOLEAN NOT NULL
);
